config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :new, :edit, :create, :update]
  resources :projects, only: [:index, :show, :new, :create]
  resources :user_projects, only: [:index, :new, :show, :create, :destroy]
  resources :project_categories, only: [:index, :show]

  post "/like_project/:project_id", to: "projects#like", as: "like_project"
  post "/like_user/:user_id", to: "users#like", as: "like_user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
    has_one_attached :song_file
    has_many :user_projects
    has_many :users, through: :user_projects

    belongs_to :like

    def is_saved_like?
      if self.like.is_liked == true
        return true
      else
        self.like.update(:is_liked => true)
        return false
      end
    end

end

app/models/project_category.rb
class ProjectCategory < ApplicationRecord
  has_many :user_projects
  has_many :users, through: :user_projects
  has_many :projects, through: :user_projects
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_projects
    has_many :projects, through: :user_projects

    validates :age, numericality:{greater_than:0, less_than: 100, only_integer: true}
    def full_name
        self.first_name + " " + self.last_name
    end
    def most_liked_songs
        self.projects.max_by{ |song| song.likes }
    end
    def least_liked_songs
        self.projects.min_by{ |song| song.likes }
    end
    def most_viewed_songs
        self.projects.max_by{ |song| song.views }
    end
    def least_viewed_songs
        self.projects.min_by{ |song| song.views }
    end
    def most_played_songs
        self.projects.max_by{ |song| song.plays }
    end
    def least_played_songs
        self.projects.min_by{ |song| song.plays }
    end
    def all_artists
        Project.all.select {|artist| artist.users == self}
    end
    def most_songs_artists
        self.all_artists.max_by{|artist| artist.projects}
    end
    def least_songs_artists
        self.all_artists.min_by{|artist| artist.projects}
    end
    def most_liked_artist
       self.all_artists.max_by{|art| art.likes}
    end
    def least_liked_artist
        self.all_artists.min_by{|art| art.likes}
    end
    def most_played_artist
        self.all_artists.max_by{|art| art.plays}
    end
    def least_played_artist
        self.all_artists.min_by{|art| art.plays}
    end
    def most_viewed_artist
        self.projects.max_by{ |art| art.views }
    end
    def least_viewed_artist
        self.projects.min_by{ |art| art.views }
    end
    def average_song_likes_of_artist
        average_likes = self.projects.map{|avg| avg.likes}
        average_likes.sum.to_f/average_likes.count
    end
    def average_song_views_of_artist
        average_views= self.projects.map{|avg| avg.views}
        average_views.sum.to_f/average_views.count
    end
    def average_song_plays_of_artist
        average_plays = self.projects.map{|avg| avg.plays}
        average_plays.sum.to_f/average_plays.count
    end

end

app/models/user_project.rb
class UserProject < ApplicationRecord
    has_one_attached :song_file
    belongs_to :user 
    belongs_to :project
    belongs_to :project_category

    accepts_nested_attributes_for :project

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/project_categories_controller.rb
class ProjectCategoriesController < ApplicationController
  def index
    @project_categories = ProjectCategory.all
  end

  def show
    @project_category = ProjectCategory.find_by(id: params[:id])
    @user_projects = UserProject.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    def index
        @projects = Project.all
    end

    def new
        @project = Project.new
        @project_categories = ProjectCategory.all
        @user_project = UserProject.new
    end

    def show
        @project = Project.find_by(id: params[:id])
        @user_projects = UserProject.all
        @project.views += 1
        @project.save
    end

    def create
        @project = Project.create(project_params)
        @user_project = UserProject.create(user_project_params)
        if @project.valid?
            @project.save
          redirect_to project_path(@project)
      else
          flash[:errors] = @project.errors.full_messages
          redirect_to new_project_path
      end
    end


    def like
        @project = Project.find(params[:project_id])
        @project.likes += 1
        @project.save

        redirect_to project_path(@project)
    end




    private

    def project_params
        params.require(:project).permit(:name, :description, :song_file, :likes, :views, :plays)
    end

    def user_project_params
        params.require(:user_project).permit(1000, :id, )
    end


end

app/controllers/user_projects_controller.rb
class UserProjectsController < ApplicationController

    def index
        @users = User.all
    end

    def new
        @user_project = UserProject.new
        @users = User.all
        @project_categories = ProjectCategory.all
        @project = @user_project.build_project
    end

    def create
        @user_project = UserProject.create(user_project_params)
        if @user_project.valid?
          redirect_to project_path(@user_project.project_id)
      else
          flash[:errors] = @user_project.errors.full_messages
          redirect_to new_user_project_path
      end

    end

    def show
        @user_project = UserProject.find_by(id: params[:id])

    end

    private

    def user_project_params
        params.require(:user_project).permit(:user_id, :project_category_id, :song_file, project_attributes: [:id, :name, :description, :likes, :views, :plays])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      redirect_to user_path(@user)
  else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
  end
end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])

    if @user.update(:first_name=> params[:user][:first_name], :last_name=> params[:user][:last_name], :age=> params[:user][:age])
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @user_projects = UserProject.all
    @user.views += 1
    @user.save
  end

  def like
    @user = User.find(params[:user_id])
    @user.likes += 1
    @user.save

    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :likes, :views, :plays)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_categories_helper.rb
module ProjectCategoriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_projects_helper.rb
module UserProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/project_categories/index.erb
<h1>Genres:</h1>

<ul>
  <% @project_categories.each do |pc| %>
    <li><%= link_to(pc.category_type, project_category_path(pc)) %></li>
  <% end %>
</ul>

app/views/project_categories/show.erb
<h1>List of <%= @project_category.category_type %> Artists</h1>

<% selected_user_projects = @user_projects.select do |up| %>
  <% up.project_category_id == @project_category.id %>
<% end %>

<ul>
  <% found = [] %>
  <% selected_user_projects.each do |selected| %>
    <% if found.include?(selected.user) == false %>
      <li><%= link_to(selected.user.first_name.to_s + " " + selected.user.last_name.to_s, user_path(selected.user)) %></li>
      <% found << selected.user %>
    <% end %>
  <% end %>
</ul>

app/views/projects/index.erb
<h1>Songs:</h1>

<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project_path(project) %></li>
  <% end %>
</ul>

app/views/projects/new.erb
<h1>Upload your song</h1>

<% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |error| %>
            <li> <%= error %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @project do |f| %>

<%= f.label "Song Name" %>
<%= f.text_field :name %>

<%= f.label "Genre" %>
<%= f.collection_select(@user_project.project_category_id, @project_categories, :id, :category_type) %> <br>

<%= f.label :description %>
<%= f.text_field :description %> <br>

<%= f.label :likes %>
<%= f.text_field :likes %> <br>

<%= f.label :views %>
<%= f.text_field :views %> <br>

<%= f.label :plays %>
<%= f.text_field :plays %> <br>

<%= f.label "Audio File" %>
<%= f.file_field :song_file %> <br>


<%= f.submit "Upload Your Song" %>
<% end %>

app/views/projects/show.erb
<h1>Song Title: <%= @project.name %></h1>

<h3>From : <%= @project.description %></h3>
<h4>Genre: <%= link_to(UserProject.find_by_project_id(@project.id).project_category.category_type, project_category_path(UserProject.find_by_project_id(@project.id).project_category)) %></h4>
<h4>Likes: <%= @project.likes %></h4>
<h4>Views: <%= @project.views %></h4>
<h4>Plays: <%= @project.plays %></h4>


<% selected_user_projects = @user_projects.select do |up| %>
  <% up.project_id == @project.id %>
<% end %>

By: <ul>
  <% found = [] %>
  <% selected_user_projects.each do |selected| %>
    <% if found.include?(selected.project) == false %>
      <li><%= link_to(selected.user.first_name.to_s + " " + selected.user.last_name.to_s, user_path(selected.user)) %></li>
      <% found << selected.user %>
    <% end %>
  <% end %>
</ul>

<%= button_to "Add a like", like_project_path(@project), :disabled => @project.is_saved_like? %>







<%= link_to("View all Projects", projects_path) %>

app/views/user_projects/edit.erb
<h1>Edit your song</h1>

<% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |error| %>
            <li> <%= error %></li>
        <% end %>
    </ul>
<% end %>
<%= form_for Project.new do |f| %>

   <%= f.label :name %>
<%= f.text_field :name %> <br>

<%= f.label :description %>
<%= f.text_field :description %> <br>

<%= f.label "Audio File" %>
<%= f.text_field :song_file %> <br>





<%= f.submit "Upload Your Song" %>
<% end %>

app/views/user_projects/index.erb
<h1>User Projects:</h1>

<ul>
  <% @user_projects.each do |project| %>
    <li><%= link_to(project.user_id.to_s + " " + project.project_id.to_s, user_project_path(project)) %></li>
  <% end %>
</ul>

app/views/user_projects/new.erb
<h1>Upload your song</h1>

<% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |error| %>
            <li> <%= error %></li>
        <% end %>
    </ul>
<% end %>
<%= form_for @user_project do |f| %>


Song
    <%= f.fields_for :project do |projects_form| %>
        <%= projects_form.label :name %>
        <%= projects_form.text_field :name, required: true %><br>

        <%= projects_form.label :description %>
        <%= projects_form.text_field :description, required: true %><br>

         <%= projects_form.label :likes %>
        <%= projects_form.text_field :likes, value: 0 %><br>

         <%= projects_form.label :views %>
        <%= projects_form.text_field :views, value: 0 %><br>

         <%= projects_form.label :plays %>
        <%= projects_form.text_field :plays, value: 0 %><br>
    <% end %><br>

<%= f.label :user_id %>
<%= f.collection_select(:user_id,@users,:id,:full_name) %> <br>

<%= f.label :project_category_id %>
<%= f.collection_select(:project_category_id,@project_categories,:id,:category_type) %> <br>

<%= f.label :song_file %>
<%= f.file_field :song_file %> <br>


<%= f.submit "Upload Your Song" %>
<% end %>

app/views/user_projects/show.erb
<h1><%= @user_project.user.full_name %></h1>
<h1><%= @user_project.project_category.category_type %></h1>

app/views/users/edit.erb
  <h1 Hi <%= @user.first_name%>! Edit your profile using the menus below: </h1>



 <% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |error| %>
            <li> <%= error %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %> <br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %> <br>

    <%= f.label :age %>
    <%= f.text_field :age %> <br>



    <%= f.submit "Update your profile" %>
<% end %>

app/views/users/index.erb
<h1>Artists:</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= link_to(user.full_name, user_path(user)) %> | Age: <%= user.age %></li>
  <% end %>
</ul>

app/views/users/new.erb
  
<h1>Sign up</h1>

<% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |error| %>
            <li> <%= error %></li>
        <% end %>
    </ul>
<% end %>
<%= form_for @user do |f| %>

   <%= f.label :first_name %>
<%= f.text_field :first_name %> <br>

<%= f.label :last_name %>
<%= f.text_field :last_name %> <br>

<%= f.label :age %>
<%= f.text_field :age %> <br>

<%= f.label :likes %>
<%= f.text_field :likes %> <br>

<%= f.label :views %>
<%= f.text_field :views %> <br>

<%= f.label :plays %>
<%= f.text_field :plays %> <br>

<%= f.submit "Create Your Profile" %>
<% end %>

app/views/users/show.erb
<h1><%= @user.first_name %> <%= @user.last_name %> Details: </h1>
<p>Age: <%= @user.age %></p>
<p>Artist Likes: <%= @user.likes %></p>
<p>Views: <%= @user.views %></p>
<p>Plays: <%= @user.plays %></p>
<p>Average of All Song Likes: <%= @user.average_song_likes_of_artist %></p>
<p>Average of All Song Views: <%= @user.average_song_views_of_artist %></p>
<p>Average of All Song Plays: <%= @user.average_song_plays_of_artist %></p>
<p>Songs:</p>
<% selected = @user_projects.select do |up| %>
  <% up.user_id == @user.id %>
<% end %>
<ul>
  <% selected.each do |select| %>
    <li><%= link_to(select.project.name, project_path(select.project)) %></li>
  <% end %>
</ul>
<%= button_to "Add a like", like_user_path(@user) %>
<br>
<h3>Highlights:</h3>
<p><%= link_to "Most Viewed Song", project_path(@user.most_viewed_songs) %></p>
<p><%= link_to "Most Liked Song", project_path(@user.most_liked_songs) %></p>
<p><%= link_to "Least Liked Song", project_path(@user.least_liked_songs) %></p>
<p><%= link_to "Least Viewed Song", project_path(@user.least_viewed_songs) %></p>
<p><%= link_to "Most Played Song", project_path(@user.most_played_songs) %></p>
<p><%= link_to "Least Played Song", project_path(@user.least_played_songs) %></p>
<br><br><br>
<%= link_to "Edit Profile", edit_user_path(@user) %><br>
<%= link_to("View All Artists", users_path) %><br>
<%= link_to("Upload Song", new_user_project_path(@user)) %>

<br>
<%= link_to("Site stats", user_projects_path)